export const initialState = {
  
  user: {
    state:'',
    authenticated: false,
  },

  posts: {
    data: [
      {
        _id: '444666999',
        author: 'Robert Jonson',
        title: 'monster in the city',
        description: 'Something to be devoured.',
        imgSrc: 'https://files.fm/thumb_show.php?i=yp5aggzvr',
        date_publ: '2020-03-09',
        email: 'robertjonson@mail.com',
        phone: '+48 555111333',
        location: 'London',
      },
      {
        _id: '4443466999',
        author: 'Mike Luke',
        title: 'monster in the city',
        description: 'Something to be devoured.',
        imgSrc: 'https://files.fm/thumb_show.php?i=bcjxqvs96',
        date_publ: '2020-07-09',
        email: 'm.l@mail.com',
        phone: '+48 555311333',
        location: 'Paris',
      },
      {
        _id: '44466456999',
        author: 'Anna Git',
        title: 'monster in the city',
        description: 'Something to be devoured.',
        imgSrc: 'https://files.fm/thumb_show.php?i=dmmbek7be',
        date_publ: '2020-03-18',
        email: 'annagit@mail.com',
        phone: '+48 555151333',
        location: 'Iran',
      },
      {
        _id: '4446665999',
        author: 'Maya Rete',
        title: 'monster in the city',
        description: 'Something to be devoured.',
        imgSrc: 'https://files.fm/thumb_show.php?i=yp5aggzvr',
        date_publ: '2021-03-09',
        email: 'retemaya@mail.com',
        phone: '+48 555113833',
        location: 'London',
      },
      {
        _id: '444666953299',
        author: 'Ricke Too',
        title: 'monster in the city',
        description: 'Something to be devoured.',
        imgSrc: 'https://files.fm/thumb_show.php?i=bcjxqvs96',
        date_publ: '2020-03-10',
        email: 'rickee@mail.com',
        phone: '+48 555881333',
        location: 'Iran',
      },
      {
        _id: '444666256999',
        author: 'Kate PEE',
        title: 'monster in the city',
        description: 'Something to be devoured.',
        imgSrc: 'https://files.fm/thumb_show.php?i=dmmbek7be',
        date_publ: '2020-04-09',
        email: 'katepiee@mail.com',
        phone: '+48 555971333',
        location: 'Warsaw',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};